build:
	g++ -Wall -Wextra crypto.cpp -o crypto
	g++ -Wall -Wextra stocks.cpp -o stocks
	g++ -Wall -Wextra valley.cpp -o valley
   
run-p1:
	./crypto

run-p2:
	./stocks

run-p3:
	./valley

clean: 
	rm crypto stocks valley
