build: tema1.o structures.o
	cl tema1.o structures.o /Feso-cpp.exe /MD /D_CRT_SECURE_NO_DEPRECATE
tema1.o: tema1.c
	cl tema1.c /c /Fotema1.o /MD /D_CRT_SECURE_NO_DEPRECATE
structures.o: structures.c
	cl structures.c /c /Fostructures.o /MD /D_CRT_SECURE_NO_DEPRECATE
